site_name: Flecto
repo_url: https://github.com/EveIsSim/Flecto
site_url: https://your-org.github.io/Flecto/
docs_dir: pages

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - diagrams

nav:
  - Home: index.md
  - Filters: filters.md
  - Validations: validations.md
  - Bindings: bindings.md
  - Usages: usages.md
  - Roadmap: roadmap.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.highlight

extra_javascript:
  - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js

plugins:
  - search
